manila_ui/dashboards/admin/share_snapshots/urls.py
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from django.conf import urls

from manila_ui.dashboards.admin.share_snapshots import views


urlpatterns = [
    urls.url(
        r'^$',
        views.ShareSnapshotsView.as_view(),
        name='index'),
    urls.url(
        r'^(?P<snapshot_id>[^/]+)$',
        views.ShareSnapshotDetailView.as_view(),
        name='share_snapshot_detail'),
]

manila_ui/dashboards/admin/shares/urls.py
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from django.conf import urls

from manila_ui.dashboards.admin.shares.replicas import views as replica_views
from manila_ui.dashboards.admin.shares import views
from manila_ui import features


urlpatterns = [
    urls.url(
        r'^$',
        views.SharesView.as_view(),
        name='index'),
    urls.url(
        r'^(?P<share_id>[^/]+)/$',
        views.DetailView.as_view(),
        name='detail'),
    urls.url(
        r'^manage$',
        views.ManageShareView.as_view(),
        name='manage'),
    urls.url(
        r'^unmanage/(?P<share_id>[^/]+)$',
        views.UnmanageShareView.as_view(),
        name='unmanage'),
]

if features.is_replication_enabled():
    urlpatterns.extend([
        urls.url(
            r'^(?P<share_id>[^/]+)/replicas/$',
            replica_views.ManageReplicasView.as_view(),
            name='manage_replicas'),
        urls.url(
            r'^replica/(?P<replica_id>[^/]+)$',
            replica_views.DetailReplicaView.as_view(),
            name='replica_detail'),
        urls.url(
            r'^replica/(?P<replica_id>[^/]+)/resync_replica$',
            replica_views.ResyncReplicaView.as_view(),
            name='resync_replica'),
        urls.url(
            r'^replica/(?P<replica_id>[^/]+)/reset_replica_status$',
            replica_views.ResetReplicaStatusView.as_view(),
            name='reset_replica_status'),
        urls.url(
            r'^replica/(?P<replica_id>[^/]+)/reset_replica_state$',
            replica_views.ResetReplicaStateView.as_view(),
            name='reset_replica_state'),
    ])

if features.is_migration_enabled():
    urlpatterns.extend([
        urls.url(
            r'^migration_start/(?P<share_id>[^/]+)$',
            views.MigrationStartView.as_view(),
            name='migration_start'),
        urls.url(
            r'^migration_complete/(?P<share_id>[^/]+)$',
            views.MigrationCompleteView.as_view(),
            name='migration_complete'),
        urls.url(
            r'^migration_cancel/(?P<share_id>[^/]+)$',
            views.MigrationCancelView.as_view(),
            name='migration_cancel'),
        urls.url(
            r'^migration_get_progress/(?P<share_id>[^/]+)$',
            views.MigrationGetProgressView.as_view(),
            name='migration_get_progress'),
    ])

manila_ui/dashboards/project/share_snapshots/urls.py
# Copyright 2017 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

from django.conf import urls

from manila_ui.dashboards.project.share_snapshots import views


urlpatterns = [
    urls.url(
        r'^$',
        views.ShareSnapshotsView.as_view(),
        name='index'),
    urls.url(
        r'^(?P<share_id>[^/]+)/share_snapshot_create/$',
        views.CreateShareSnapshotView.as_view(),
        name='share_snapshot_create'),
    urls.url(
        r'^(?P<snapshot_id>[^/]+)/share_snapshot_edit/$',
        views.UpdateShareSnapshotView.as_view(),
        name='share_snapshot_edit'),
    urls.url(
        r'^(?P<snapshot_id>[^/]+)$',
        views.ShareSnapshotDetailView.as_view(),
        name='share_snapshot_detail'),
    urls.url(
        r'^(?P<snapshot_id>[^/]+)/share_snapshot_rules/$',
        views.ManageShareSnapshotRulesView.as_view(),
        name='share_snapshot_manage_rules'),
    urls.url(
        r'^(?P<snapshot_id>[^/]+)/share_snapshot_rule_add/$',
        views.AddShareSnapshotRuleView.as_view(),
        name='share_snapshot_rule_add'),
]

manila_ui/dashboards/project/shares/forms.py
# Copyright (c) 2014 NetApp, Inc.
# All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from django.conf import settings
from django.forms import ValidationError
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from horizon import exceptions
from horizon import forms
from horizon import messages
from horizon.utils.memoized import memoized

from manila_ui.api import manila
from manila_ui.dashboards import utils
from manila_ui import features
from manilaclient.common.apiclient import exceptions as m_exceptions
import time


class CreateForm(forms.SelfHandlingForm):
    name = forms.CharField(max_length="255", label=_("Share Name"))
    description = forms.CharField(
        label=_("Description"), required=False,
        widget=forms.Textarea(attrs={'rows': 3}))
    share_proto = forms.ChoiceField(label=_("Share Protocol"), required=True)
    size = forms.IntegerField(min_value=1, label=_("Size (GiB)"))
    share_type = forms.ChoiceField(
        label=_("Share Type"), required=True,
        widget=forms.Select(
            attrs={'class': 'switchable', 'data-slug': 'sharetype'}))

    def __init__(self, request, *args, **kwargs):
        super(CreateForm, self).__init__(request, *args, **kwargs)
        # NOTE(vkmc): choose only those share protocols that are enabled
        # FIXME(vkmc): this should be better implemented by having a
        # capabilities endpoint on the control plane.
        manila_features = getattr(settings, 'OPENSTACK_MANILA_FEATURES', {})
        self.enabled_share_protocols = manila_features.get(
            'enabled_share_protocols',
            ['NFS', 'CIFS', 'GlusterFS', 'HDFS', 'CephFS', 'MapRFS'])
        self.enable_public_shares = manila_features.get(
            'enable_public_shares', True)
        share_networks = manila.share_network_list(request)
        share_types = manila.share_type_list(request)
        self.fields['share_type'].choices = (
            [(st.name, st.name) for st in share_types])

        if features.is_share_groups_enabled():
            share_groups = manila.share_group_list(request)
            self.fields['sg'] = forms.ChoiceField(
                label=_("Share Group"),
                choices=[("", "")] + [(sg.id, sg.name or sg.id)
                                      for sg in share_groups],
                required=False)

        self.sn_field_name_prefix = 'share-network-choices-'
        for st in share_types:
            extra_specs = st.get_keys()
            dhss = extra_specs.get('driver_handles_share_servers')
            # NOTE(vponomaryov): Set and tie share-network field only for
            # share types with enabled handling of share servers.
            if (isinstance(dhss, str) and dhss.lower() in ['true', '1']):
                sn_choices = (
                    [('', '')] +
                    [(sn.id, sn.name or sn.id) for sn in share_networks])
                sn_field_name = (
                    self.sn_field_name_prefix +
                    utils.transform_dashed_name(st.name)
                )
                sn_field = forms.ChoiceField(
                    label=_("Share Network"), required=True,
                    choices=sn_choices,
                    widget=forms.Select(attrs={
                        'class': 'switched',
                        'data-switch-on': 'sharetype',
                        'data-sharetype-%s' % utils.transform_dashed_name(
                            st.name): _("Share Network"),
                    }))
                self.fields[sn_field_name] = sn_field

        self.fields['share_source_type'] = forms.ChoiceField(
            label=_("Share Source"), required=False,
            widget=forms.Select(
                attrs={'class': 'switchable', 'data-slug': 'source'}))
        self.fields['snapshot'] = forms.ChoiceField(
            label=_("Use snapshot as a source"),
            widget=forms.fields.SelectWidget(
                attrs={'class': 'switched',
                       'data-switch-on': 'source',
                       'data-source-snapshot': _('Snapshot')},
                data_attrs=('size', 'name'),
                transform=lambda x: "%s (%sGiB)" % (x.name, x.size)),
            required=False)
        self.fields['metadata'] = forms.CharField(
            label=_("Metadata"), required=False,
            widget=forms.Textarea(attrs={'rows': 4}))

        if self.enable_public_shares:
            self.fields['is_public'] = forms.BooleanField(
                label=_("Make visible to users from all projects"),
                required=False)

        self.fields['share_proto'].choices = [(sp, sp) for sp in
                                              self.enabled_share_protocols]
        if ("snapshot_id" in request.GET or
                kwargs.get("data", {}).get("snapshot")):
            try:
                snapshot = self.get_snapshot(
                    request,
                    request.GET.get("snapshot_id",
                                    kwargs.get("data", {}).get("snapshot")))
                self.fields['name'].initial = snapshot.name
                self.fields['size'].initial = snapshot.size
                self.fields['snapshot'].choices = ((snapshot.id, snapshot),)
                try:
                    # Set the share type and az from the original share
                    orig_share = manila.share_get(request, snapshot.share_id)
                    self.fields['share_type'].initial = (
                        orig_share.share_type_name)
                    self.fields['availability_zone'].initial = (
                        orig_share.availability_zone)
                except Exception:
                    pass
                self.fields['size'].help_text = _(
                    'Share size must be equal to or greater than the snapshot '
                    'size (%sGiB)') % snapshot.size
                del self.fields['share_source_type']
            except Exception:
                exceptions.handle(request,
                                  _('Unable to load the specified snapshot.'))
        else:
            source_type_choices = []

            try:
                snapshot_list = manila.share_snapshot_list(request)
                snapshots = [s for s in snapshot_list
                             if s.status == 'available']
                if snapshots:
                    source_type_choices.append(("snapshot",
                                                _("Snapshot")))
                    choices = [('', _("Choose a snapshot"))] + \
                              [(s.id, s) for s in snapshots]
                    self.fields['snapshot'].choices = choices
                else:
                    del self.fields['snapshot']
            except Exception:
                exceptions.handle(request, _("Unable to retrieve "
                                             "share snapshots."))

            if source_type_choices:
                choices = ([('no_source_type',
                             _("No source, empty share"))] +
                           source_type_choices)
                self.fields['share_source_type'].choices = choices
            else:
                del self.fields['share_source_type']

    def clean(self):
        cleaned_data = super(CreateForm, self).clean()
        form_errors = list(self.errors)

        chosen_share_type = cleaned_data.get('share_type')
        if chosen_share_type:
            # NOTE(vponomaryov): skip errors for share-network fields that are
            # not related to chosen share type.
            for error in form_errors:
                st_name = error.split(self.sn_field_name_prefix)[-1]
                if (error.startswith(self.sn_field_name_prefix) and
                        st_name != chosen_share_type):
                    cleaned_data[error] = 'Not set'
                    self.errors.pop(error, None)

            cleaned_data['share_network'] = cleaned_data.get(
                self.sn_field_name_prefix + cleaned_data.get('share_type'))

        return cleaned_data

    def handle(self, request, data):
        try:
            snapshot_id = None
            source_type = data.get('share_source_type', None)
            share_network = data.get('share_network', None)
            if (data.get("snapshot", None) and
                    source_type in [None, 'snapshot']):
                # Create from Snapshot
                snapshot = self.get_snapshot(request,
                                             data["snapshot"])
                snapshot_id = snapshot.id
                if (data['size'] < snapshot.size):
                    error_message = _('The share size cannot be less than the '
                                      'snapshot size (%sGiB)') % snapshot.size
                    raise ValidationError(error_message)
            else:
                data['size'] = int(data['size'])

            metadata = {}
            try:
                set_dict, unset_list = utils.parse_str_meta(data['metadata'])
                if unset_list:
                    msg = _("Expected only pairs of key=value.")
                    raise ValidationError(message=msg)
                metadata = set_dict
            except ValidationError as e:
                self.api_error(e.messages[0])
                return False
            is_public = self.enable_public_shares and data['is_public']
            share = manila.share_create(

manila_ui/dashboards/admin/share_snapshots/views.py
# Copyright 2017 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""
Admin views for managing share snapshots.
"""

from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from horizon import exceptions
from horizon import tables
from horizon.utils import memoized

from manila_ui.api import manila
from manila_ui.dashboards.admin.share_snapshots import tables as ss_tables
from manila_ui.dashboards.admin.share_snapshots import tabs as ss_tabs
from manila_ui.dashboards.admin import utils
import manila_ui.dashboards.project.share_snapshots.views as snapshot_views


class ShareSnapshotsView(tables.MultiTableView):
    table_classes = (
        ss_tables.ShareSnapshotsTable,
    )
    template_name = "admin/share_snapshots/index.html"
    page_title = _("Share Snapshots")

    @memoized.memoized_method
    def get_share_snapshots_data(self):
        snapshots = []
        try:
            snapshots = manila.share_snapshot_list(
                self.request, search_opts={'all_tenants': True})
            shares = manila.share_list(self.request)
            share_names = dict([(share.id, share.name or share.id)
                                for share in shares])
            for snapshot in snapshots:
                snapshot.share = share_names.get(snapshot.share_id)
        except Exception:
            msg = _("Unable to retrieve share snapshot list.")
            exceptions.handle(self.request, msg)

        # Gather our projects to correlate against IDs
        utils.set_project_name_to_objects(self.request, snapshots)

        return snapshots


class ShareSnapshotDetailView(snapshot_views.ShareSnapshotDetailView):
    tab_group_class = ss_tabs.SnapshotDetailTabs
    template_name = "admin/share_snapshots/detail.html"
    redirect_url = reverse_lazy("horizon:admin:share_snapshots:index")

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/_create.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block modal-body-right %}
  <div class="quota-dynamic">
    {% include "project/share_snapshots/_limits.html" with usages=usages snapshot_quota=True %}
  </div>
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/_detail.html
{% load i18n sizeformat parse_date %}

<h3>{% trans "Snapshot Overview" %}</h3>
<div class="detail">
  <hr class="header_rule">
  <dl class="dl-horizontal">
    <dt>{% trans "Name" %}</dt>
    <dd>{{ snapshot.name }}</dd>
    <dt>{% trans "ID" %}</dt>
    <dd>{{ snapshot.id }}</dd>
    {% url 'horizon:project:shares:detail' snapshot.share_id as share_url %}
    <dt>{% trans "Source" %}</dt>
    <dd><a href="{{ share_url }}">{{ snapshot.share_name_or_id }}</a></dd>
    {% if snapshot.description %}
    <dt>{% trans "Description" %}</dt>
    <dd>{{ snapshot.description }}</dd>
    {% endif %}
    <dt>{% trans "Status" %}</dt>
    <dd>{{ snapshot.status|capfirst }}</dd>
    {% if snapshot.export_locations %}
    <dt>{% trans "Export locations" %}</dt>
    {% for el in snapshot.export_locations %}
      <dd><p>
        <div><b>{% trans "Path:" %}</b>
            <input type="text" readonly="true"
                   value="{{ el.path }}" size="{{ snapshot.el_size }}"
                   onClick="this.setSelectionRange(0, this.value.length)">
        </div>
        {% if el.is_admin_only != None %}
        <div><b>{% trans "Is admin only:" %}</b> {{ el.is_admin_only }}</div>
        {% endif %}
        {% if el.share_snapshot_instance_id %}
        <div><b>{% trans "Snapshot Replica ID:" %}</b> {{ el.share_snapshot_instance_id }}</div>
        {% endif %}
      </p></dd>
    {% endfor %}
    {% endif %}
  </dl>
</div>

{% if snapshot.rules != None %}
<div class="detail">
  <h4>{% trans "Access Rules" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
  {% for rule in snapshot.rules %}
    <dt>{{ rule.access_type }}</dt>
    <dd><p>
      <div><b>{% trans "Access to:" %} </b>{{ rule.access_to }}</div>
      <div><b>{% trans "Status:" %} </b>{{ rule.state }}</div>
    </p></dd>
  {% endfor %}
  </dl>
</div>
{% endif %}

<div class="detail">
  <h4>{% trans "Specs" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
    <dt>{% trans "Size" %}</dt>
    <dd>{{ snapshot.size }} {% trans "GiB" %}</dd>
    <dt>{% trans "Created" %}</dt>
    <dd>{{ snapshot.created_at|parse_date }}</dd>
  </dl>
</div>

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/_limits.html
{% load i18n horizon humanize %}

<h3>{% trans "Description" %}:</h3>

<p>{% trans "Share Snapshots are used for storing share changes and creating shares. " %}</p>

<h3>{% trans "Share Limits" %}</h3>

<div class="quota_title clearfix">
  <strong>{% trans "Total Gibibytes" %} <span>({{ usages.totalShareGigabytesUsed|intcomma }} {% trans "GiB" %})</span></strong>
  <p>{{ usages.maxTotalShareGigabytes|quota:_("GiB")|intcomma }}</p>
</div>

<div id="quota_size" data-progress-indicator-for="id_size" data-quota-limit="{{ usages.maxTotalShareGigabytes }}" data-quota-used="{{ usages.totalShareGigabytesUsed }}" class="quota_bar">
</div>

<div class="quota_title clearfix">
  <strong>{% trans "Number of Share Snapshots" %} <span>({{ usages.totalShareSnapshotsUsed|intcomma }})</span></strong>
  <p>{{ usages.maxTotalShareSnapshots|quota|intcomma }}</p>
</div>

<div id="quota_snapshots" data-progress-indicator-step-by="1" data-quota-limit="{{ usages.maxTotalShareSnapshots}}" data-quota-used="{{ usages.totalShareSnapshotsUsed }}" class="quota_bar">
</div>


<script type="text/javascript" charset="utf-8">
  if(typeof horizon.Quota !== 'undefined') {
    horizon.Quota.init();
  } else {
    addHorizonLoadEvent(function() {
      horizon.Quota.init();
    });
  }
</script>

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/_rule_add.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block modal-body-right %}
  <h3>{% trans "Description" %}:</h3>
  <p>{% blocktrans trimmed %}
      Add policy rule to snapshot, 'cephx' rule represents ceph auth ID.
      certificate.
    {% endblocktrans %}</p>
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/_update.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block modal-body-right %}
  <h3>{% trans "Description" %}:</h3>
  <p>{% trans "From here you can modify name and description of a snapshot." %}</p>
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/create.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Create Share Snapshot" %}{% endblock %}

{% block main %}
    {% include 'project/share_snapshots/_create.html' %}
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Share Snapshot Details" %}{% endblock %}

{% block main %}
<div class="row">
  <div class="col-sm-12">
  {{ tab_group.render }}
  </div>
</div>
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Share Snapshots" %}{% endblock %}

{% block main %}
<div class="row">
  <div class="col-sm-12">
  {{ share_snapshots_table.render }}
  </div>
</div>
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/manage_rules.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Share Snapshot Rules" %}{% endblock %}

{% block main %}
  {{ table.render }}
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/rule_add.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Add Rule" %}{% endblock %}

{% block main %}
    {% include 'project/share_snapshots/_rule_add.html' %}
{% endblock %}

manila_ui/dashboards/project/share_snapshots/templates/share_snapshots/update.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Edit Share Snapshot" %}{% endblock %}

{% block main %}
    {% include 'project/share_snapshots/_update.html' %}
{% endblock %}